spring.application.name=Autonation-USA

#port
server.port=8081

#context-path
server.servlet.context-path=/autonation

#SMTP configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akashmaurya032@gmail.com
spring.mail.password=fqflbzhmhfyntvec
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#view resolver
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp

#Datasource props
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/AutonationDB
spring.datasource.username = root
spring.datasource.password = Akash@123


#Hikari props
spring.datasource.hikari.connectionTimeout = 20000
spring.datasource.hikari.maxPoolSize = 5


#hibernate prop

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.show_sql=true